import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Preview,
  Section,
  Text,
  Tailwind,
} from "@react-email/components";
import * as React from "react";

export const ForgetPasswordEmailTemplate = (token: string) => {
  const baseUrl = process.env.NEXT_PUBLIC_ENVIRONMENT === "development" ? "http://localhost:3000" : "https://www.viewus.in"

  return (
    <Html>
      <Head />
      <Preview>Welcome to viewUs - Amplify Your Social Proof</Preview>
      <Tailwind
        config={{
          theme: {
            extend: {
              colors: {
                brand: "#4F46E5",
                offwhite: "#F9FAFB",
              },
              spacing: {
                0: "0px",
                4: "16px",
                6: "24px",
                8: "32px",
                12: "48px",
              },
            },
          },
        }}
      >
        <Body className="bg-offwhite text-base font-sans">
          <Container className="mx-auto pt-12 pb-12">
            <Img
              src="https://viewus.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo1.f089c85f.png&w=64&q=75"
              width="150"
              height="100"
              alt="viewUs"
              className="mx-auto mb-12"
            />
            <Container className="bg-white p-12 rounded-lg shadow-lg">
              <Heading className="text-center text-3xl font-bold text-gray-800 mb-6">
                Looks like you forget your password!!
              </Heading>

              <Text className="text-gray-600 mb-6">
                if this was not generated by you, please ignore this mail
              </Text>

              <Section className="text-center mb-8">
                <Button
                  href={`${baseUrl}/forget-password?token=${token}`}
                  className="bg-brand text-white font-bold py-3 px-6 rounded-full hover:bg-indigo-600 transition-colors"
                >
                  Reset your password
                </Button>
              </Section>

              <Text className="text-gray-600 mb-6">
                Need help? Our support team is always here to assist you. Feel
                free to reach out to us at{" "}
                <span className="text-brand">team@viewus.in</span>.
              </Text>
            </Container>

            <Container className="mt-8 text-center text-gray-500 text-sm">
              <Text>© 2024 viewUs. All rights reserved.</Text>
            </Container>
          </Container>
        </Body>
      </Tailwind>
    </Html >
  );
};
